name: validate-gentx
on:
  pull_request:
    # branches: [dev]
  push:
    # main
jobs:
  build:
    name: Validating
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    steps:
      - name: 'Setup jq'
        uses: dcarbone/install-jq-action@v2
      - uses: actions/checkout@v2
      - name: add permission
        run: chmod +x ./scripts/validate-gentx.sh
      - name: Validating...
        run: ./scripts/validate-gentx.sh
